server.port: 8080

canal:
  ip: 127.0.0.1
  host: 11111
  username:
  password:
  serverMode: tcp
  destinations: ask-bar,course-study,exam,human-resource,system,train,zxy-log


spring:
  datasource:
    quick-report:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://127.0.0.1:3306/quick-report?serverTimezone=GMT%2B8&autoReconnect=true&allowMultiQueries=true
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    course-study:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://127.0.0.1:3306/course-study?serverTimezone=GMT%2B8&autoReconnect=true&allowMultiQueries=true
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    report-binlog:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://127.0.0.1:3306/report-binlog?serverTimezone=GMT%2B8&autoReconnect=true&allowMultiQueries=true
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.xzb.product: debug
